encoding: UTF-8

# Site settings
title:       "COMET Lab"
author:      Changhyun Kwon
description: "Computational Optimization Methods Lab, Industrial and Systems Engineering, KAIST"
baseurl:     ""
url:         "https://comet.kaist.ac.kr"
date_format: "%b %-d, %Y"


# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md